import { StyleSheet } from '@react-pdf/renderer';

export const colors = {
  teal: '#1B8FA0',
  tealLight: '#5FB0BF',
  dark: '#0A1A1E',
  muted: '#6B7479',
  light: '#F3F6F7',
  border: '#E3E8EA',
  orange: '#E67E22',
};

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 50,
    paddingHorizontal: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: colors.dark,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: `2px solid ${colors.teal}`,
    paddingBottom: 12,
    marginBottom: 18,
  },
  logo: {
    width: 90,
    height: 'auto',
  },
  headerMeta: {
    textAlign: 'right',
    fontSize: 9,
    color: colors.muted,
  },
  titleEyebrow: {
    fontSize: 9,
    color: colors.teal,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  title: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: colors.dark,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: colors.teal,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
    marginTop: 16,
  },
  infoBlock: {
    backgroundColor: colors.light,
    padding: 12,
    borderRadius: 4,
    marginBottom: 8,
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: 3,
  },
  infoLabel: {
    width: 110,
    color: colors.muted,
    fontSize: 9,
  },
  infoValue: {
    flex: 1,
    fontSize: 10,
  },
  table: {
    border: `1px solid ${colors.border}`,
    borderRadius: 4,
    marginTop: 6,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: colors.light,
    borderBottom: `1px solid ${colors.border}`,
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  tableHeaderCell: {
    fontSize: 9,
    color: colors.muted,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: `1px solid ${colors.border}`,
    paddingVertical: 8,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  tableRowLast: {
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  signatureBox: {
    width: 130,
    height: 60,
    border: `1px solid ${colors.border}`,
    borderRadius: 3,
    backgroundColor: '#fff',
    padding: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signatureImage: {
    maxWidth: 124,
    maxHeight: 54,
    objectFit: 'contain',
  },
  signatureMissing: {
    color: colors.muted,
    fontSize: 9,
    fontStyle: 'italic',
  },
  question: {
    marginBottom: 14,
  },
  questionLabel: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 11,
    marginBottom: 4,
  },
  questionAnswer: {
    fontSize: 10,
    color: colors.dark,
    paddingLeft: 12,
    borderLeft: `2px solid ${colors.border}`,
  },
  questionCorrect: {
    fontSize: 9,
    color: colors.teal,
    paddingLeft: 12,
    marginTop: 3,
    fontStyle: 'italic',
  },
  badge: {
    backgroundColor: colors.teal,
    color: '#fff',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 10,
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Helvetica-Bold',
  },
  badgeMuted: {
    backgroundColor: colors.light,
    color: colors.muted,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 10,
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  footer: {
    position: 'absolute',
    left: 40,
    right: 40,
    bottom: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 8,
    color: colors.muted,
    borderTop: `1px solid ${colors.border}`,
    paddingTop: 8,
  },
});
