-- =============================================================================
--  Migration : enrichissement complet de la table formations
--  Date : 2026-05-05
--  À exécuter UNE FOIS dans le SQL Editor de Supabase.
--  Idempotent : ALTER ... IF NOT EXISTS + INSERT ... ON CONFLICT DO UPDATE
-- =============================================================================

-- -----------------------------------------------------------------------------
--  1. Étendre la table formations avec toutes les données pédagogiques
-- -----------------------------------------------------------------------------

ALTER TABLE public.formations
  ADD COLUMN IF NOT EXISTS sous_titre text,
  ADD COLUMN IF NOT EXISTS ref text,
  ADD COLUMN IF NOT EXISTS hero_image text,
  ADD COLUMN IF NOT EXISTS hero_alt text,
  ADD COLUMN IF NOT EXISTS duree text,
  ADD COLUMN IF NOT EXISTS public_concerne text,
  ADD COLUMN IF NOT EXISTS public_detail text,
  ADD COLUMN IF NOT EXISTS prerequis text,
  ADD COLUMN IF NOT EXISTS prix_indicatif text,
  ADD COLUMN IF NOT EXISTS modalite text,
  ADD COLUMN IF NOT EXISTS inscription text,
  ADD COLUMN IF NOT EXISTS recyclage text,
  ADD COLUMN IF NOT EXISTS objectifs text,
  ADD COLUMN IF NOT EXISTS programme jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS evaluation text,
  ADD COLUMN IF NOT EXISTS references_reglementaires text,
  ADD COLUMN IF NOT EXISTS formations_liees jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS seo_title text,
  ADD COLUMN IF NOT EXISTS seo_description text,
  ADD COLUMN IF NOT EXISTS ordre int DEFAULT 0,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- -----------------------------------------------------------------------------
--  2. Trigger pour maintenir updated_at à chaque update
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.formations_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_formations_updated_at ON public.formations;
CREATE TRIGGER trg_formations_updated_at
  BEFORE UPDATE ON public.formations
  FOR EACH ROW EXECUTE FUNCTION public.formations_set_updated_at();

-- -----------------------------------------------------------------------------
--  3. Données — UPSERT des 17 formations
-- -----------------------------------------------------------------------------


-- Formation Incendie — Extincteur & Évacuation
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'incendie-extincteur-evacuation',
  'Formation Incendie',
  'Extincteur & Évacuation',
  'securite',
  'SECU-01',
  '/images/formations/incendie.jpg',
  'Extincteur à eau pulvérisée — équipement de lutte contre l''incendie',
  '2 heures ou 5 heures',
  'Tout public',
  NULL,
  'Avoir 18 ans — Savoir lire et écrire',
  'Express 2h : 80 € HT (indiv.) · 450 € (4-6) · 700 € (7-10) — Complet 5h : 150 € HT (indiv.) · 800 € (4-6) · 1 200 € (7-10)',
  'Présentiel — sur site client',
  '24h avant la session',
  NULL,
  'À la fin de cette formation, le stagiaire est capable de prévenir les risques d''incendie, mettre en œuvre les moyens d''extinction disponibles en attendant les secours, et procéder à l''évacuation de l''établissement en appliquant les consignes générales de sécurité.',
  '[{"titre":"Prévention du risque incendie","points":["Le triangle du feu, classes de feux","Causes courantes d''incendie en entreprise","Comportement du feu et propagation","Consignes générales de sécurité"]},{"titre":"Moyens d''extinction","points":["Les différents types d''extincteurs","Choix de l''extincteur selon la classe de feu","Mise en œuvre pratique — manipulation sur feu réel"]},{"titre":"Évacuation","points":["Rôles : guide-file, serre-file, chargé d''évacuation","Procédure et points de rassemblement","Mise en situation — exercice d''évacuation simulé"]}]'::jsonb,
  'Attestation de formation et notification sur le registre de sécurité. Évaluation continue + mise en situation incendie simulée.',
  'Articles R4227-28, R4227-39 et R4141-17 à R4141-20 du Code du Travail — Articles L4141-2, R4141-3 et R4141-13 (formation à la sécurité) — Recommandation APSAD R6.',
  '["habilitation-electrique-h0-b0","formateur-incendie-gestes-postures"]'::jsonb,
  'Formation Incendie — Extincteur & Évacuation | C-KIM Formation',
  'Formation incendie certifiée à Draguignan (PACA). Manipulation d''extincteurs, évacuation, conformité Code du travail. Sur site, 2h ou 5h.',
  true,
  10
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Gestes et Postures — Prévention des TMS
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'gestes-et-postures',
  'Gestes et Postures',
  'Prévention des TMS',
  'securite',
  'SECU-02',
  '/images/formations/gestes-et-postures.jpg',
  'Formation Gestes et Postures — manipulation d''un transpalette en entrepôt avec gants de protection',
  '7 heures',
  'Tout salarié amené à faire de la manutention manuelle ou à travailler dans des postures contraignantes — groupe de 4 à 12 personnes',
  'Tout salarié amené à faire de la manutention manuelle ou à travailler dans des postures contraignantes. Programme adapté à votre activité — un audit préalable de vos postes de travail permet de cibler les mauvaises postures constatées.',
  'Maîtrise orale et écrite du français.',
  '200 € HT (indiv.) · 850 € HT (4-6 pers.) · 1 300 € HT (7-10 pers.)',
  'Présentiel — sur site client',
  '7 jours avant la session, sous réserve des places disponibles',
  NULL,
  'À la fin de cette formation, le stagiaire est capable d''analyser et repérer dans son poste de travail les gestes et postures sources de troubles musculosquelettiques, d''appliquer les principes de sécurité physique et d''économie d''effort, et de mobiliser des charges en utilisant des méthodes et moyens adaptés et sécurisants.',
  '[{"titre":"Accidents du travail et maladies professionnelles","points":["Définition, statistiques, enjeux humains et financiers","Obligations réglementaires et responsabilités de l''employeur","Notions d''anatomie, physiologie et pathologie","Les troubles musculosquelettiques (TMS)","Conséquences sur la santé"]},{"titre":"Prévention des risques","points":["Facteurs d''usure et de fatigue","Principes généraux de prévention","Principes de base de la manutention"]},{"titre":"Techniques pratiques","points":["Techniques de lever-porter de charge","Principes d''aménagement des postes de travail","Différents gestes et postures sur le poste"]}]'::jsonb,
  'Évaluation continue par ateliers pratiques tout au long de la formation. Évaluation formative basée sur les critères du référentiel interne C-KIM. Attestation de formation et d''assiduité, notification sur le registre de sécurité.',
  'Articles R.4541-8 et R.231-71 du Code du travail : analyse des activités de manutention, formation des salariés aux principes de sécurité physique, adaptation des moyens de prévention. Recommandation INRS : formation pratique centrée sur les gestes adaptés à chaque poste. Pour la logistique et les entrepôts, recommandation R308.',
  '["sst-initiale","mac-sst","formateur-incendie-gestes-postures"]'::jsonb,
  'Formation Gestes et Postures — Prévention TMS | C-KIM Formation',
  'Formation gestes et postures — 7h, prévention des TMS et manutention manuelle. Programme adapté à votre activité. Présentiel sur site, région PACA.',
  true,
  20
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Sauveteur Secouriste du Travail — Formation initiale
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'sst-initiale',
  'Sauveteur Secouriste du Travail',
  'Formation initiale',
  'securite',
  'SECU-03',
  '/images/formations/sst-initiale.jpg',
  'Formation SST — mannequin de réanimation pour apprentissage des gestes de premiers secours',
  '14 heures',
  'Tout public — groupe de 4 à 10 personnes',
  'Tout salarié souhaitant devenir Sauveteur Secouriste du Travail. Sessions de 4 à 10 personnes (la session est annulée si l''effectif minimum n''est pas atteint).',
  'Aucun prérequis nécessaire',
  '250 € HT (indiv.) · 1 100 € HT (4-6 pers.) · 1 600 € HT (7-10 pers.)',
  'Présentiel — sur site client',
  '7 jours avant la session, sous réserve des places disponibles',
  'MAC SST tous les 24 mois pour conserver la validité du certificat',
  'À la fin de la formation, le stagiaire est capable d''intervenir de façon adaptée face à une situation d''accident du travail et de mettre en application ses compétences de SST au service de la prévention des risques professionnels dans son entreprise.',
  '[{"titre":"Prévention","points":["Situer le cadre juridique de son intervention","Situer son rôle de SST dans l''organisation de la prévention de l''entreprise","Contribuer à la mise en œuvre d''actions de prévention","Informer les personnes désignées dans le plan d''organisation de la prévention de l''entreprise des situations dangereuses repérées"]},{"titre":"Secours","points":["Réaliser une protection adaptée","Examiner la victime","Faire alerter ou alerter les secours","Secourir les victimes de manière appropriée"]}]'::jsonb,
  'Évaluation continue par ateliers pratiques tout au long de la formation. Évaluation formative et épreuves certificatives conformes au document de référence de l''INRS. Le certificat SST est délivré aux participants ayant suivi l''intégralité de la formation et satisfait à l''ensemble des épreuves certificatives.',
  'Article R4224-16 du Code du travail et document de référence en vigueur de l''INRS. Le certificat SST est valable 24 mois — un MAC SST doit être suivi avant la fin de cette période pour prolonger la validité.',
  '["mac-sst","gestes-et-postures","formateur-sst"]'::jsonb,
  'Formation SST — Sauveteur Secouriste du Travail | C-KIM Formation',
  'Formation initiale SST certifiante — 14h, conforme INRS. Prévention et secours en entreprise. Présentiel sur site, région PACA.',
  true,
  30
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- MAC Sauveteur Secouriste du Travail — Maintien & Actualisation des Compétences
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'mac-sst',
  'MAC Sauveteur Secouriste du Travail',
  'Maintien & Actualisation des Compétences',
  'securite',
  'SECU-04',
  '/images/formations/mac-sst.jpg',
  'MAC SST — manipulation d''un défibrillateur, recyclage et actualisation des compétences SST',
  '7 heures',
  'Personnel titulaire d''un certificat de Sauveteur Secouriste du Travail — groupe de 4 à 10 personnes',
  'Personnel ayant suivi la formation SST initiale et devant maintenir la validité de son certificat. Sessions de 4 à 10 personnes.',
  'Être titulaire du certificat SST, ou d''un certificat APS ASD, APS TRV ou TRM en cours de validité (ou non).',
  '150 € HT (indiv.) · 650 € HT (4-6 pers.) · 900 € HT (7-10 pers.)',
  'Présentiel — sur site client',
  '7 jours avant la session, sous réserve des places disponibles',
  'Obligatoire tous les 24 mois pour conserver la validité du certificat SST',
  'À la fin de cette formation, le stagiaire est capable d''actualiser ses connaissances en matière de secourisme et de prévention.',
  '[{"titre":"Échange des pratiques","points":["Échanger sur ses pratiques en tant que SST","S''approprier les nouveautés du document de référence et du guide des données techniques de l''INRS et du réseau prévention"]},{"titre":"Prévention","points":["Identifier les risques de l''entreprise ou de l''établissement","Identifier les risques spécifiques au secteur d''activité"]},{"titre":"Secours","points":["Réaliser une protection adaptée","Examiner la victime","Faire alerter ou alerter les secours","Secourir les victimes de manière appropriée"]}]'::jsonb,
  'Évaluation continue par ateliers pratiques tout au long de la formation. Évaluation formative et épreuves certificatives conformes au document de référence de l''INRS. Le certificat SST est prolongé pour 24 mois aux participants ayant satisfait aux épreuves.',
  'Article R4224-16 du Code du travail et document de référence en vigueur de l''INRS. Le certificat SST est valable 24 mois — un MAC doit être validé avant la fin de cette période pour le prolonger.',
  '["sst-initiale","gestes-et-postures","formateur-sst"]'::jsonb,
  'MAC SST — Maintien et Actualisation des Compétences SST | C-KIM Formation',
  'Recyclage SST — 7h, conforme INRS, tous les 24 mois. Prolongez la validité de votre certificat de Sauveteur Secouriste du Travail. Sur site, région PACA.',
  true,
  40
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Habilitation Électrique — H0 – B0
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'habilitation-electrique-h0-b0',
  'Habilitation Électrique',
  'H0 – B0',
  'securite',
  'SECU-06',
  '/images/formations/habilitation-electrique-h0-b0.jpg',
  'Tableau électrique professionnel et formation à l''habilitation H0-B0',
  '7 heures (1 jour)',
  'Tout public — exécutants de travaux non électriques',
  NULL,
  'Aucun',
  '200 € HT (indiv.) · 850 € HT (4-6 pers.) · 1 300 € HT (7-10 pers.)',
  'Présentiel',
  '7 jours avant',
  'Tous les 3 ans (préconisation NF C18-510)',
  'À l''issue de la formation, le stagiaire est capable de connaître le risque électrique inhérent à l''exécution de travaux non électriques dans les locaux réservés aux électriciens ou au voisinage de pièces nues sous tension (B0V / H0V), d''exécuter en sécurité des opérations d''ordre non électrique en BT dans le respect des prescriptions de sécurité, de prévenir ou agir face à un accident d''origine électrique, et de respecter les prescriptions de sécurité définies par la publication UTE C 18-510.',
  '[{"titre":"Aspects réglementaires","points":["Décret du 14 novembre 1988 — version consolidée","Publication UTE C 18-510 et normes électriques","Obligations, responsabilités, domaines d''application","Procédure d''habilitation H0V / B0V et ses limites"]},{"titre":"Notions élémentaires d''électricité & risques","points":["Notions de tension, intensité, résistance","Classement des installations électriques","Dangers de l''électricité — exemples d''accidents réels","Mécanisme d''électrisation — résistance du corps humain"]},{"titre":"Prévention du risque électrique","points":["Moyens de protection contre les contacts directs et indirects","Mesures de protection de l''installation électrique","Règles de sécurité générale en électricité","Protection lors de l''utilisation de matériels électriques amovibles"]},{"titre":"Conduite à tenir en cas d''accident électrique","points":["Protéger, alerter, secourir — réflexes d''urgence","Notions de 1er secours adaptées aux accidents électriques","Incendie sur un ouvrage électrique — conduite à tenir"]}]'::jsonb,
  'QCM d''aptitude en fin de formation. Attestation de formation délivrée. L''employeur délivre ensuite l''habilitation H0/B0.',
  'Norme NF C18-510 — Décret du 14 novembre 1988 (version consolidée) — Publication UTE C 18-510 — Articles R4544-9 et R4544-10 du Code du travail.',
  '["habilitation-electrique-b1v-b2v","incendie-extincteur-evacuation"]'::jsonb,
  'Habilitation Électrique H0-B0 | C-KIM Formation',
  'Formation Habilitation Électrique H0-B0 conforme NF C18-510. 7h, présentiel, à Draguignan (PACA). Pour exécutants de travaux d''ordre non électrique en BT.',
  true,
  50
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Habilitation Électrique — B1V & B2V — Basse Tension
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'habilitation-electrique-b1v-b2v',
  'Habilitation Électrique',
  'B1V & B2V — Basse Tension',
  'securite',
  'SECU-06',
  '/images/formations/habilitation-electrique-b1v-b2v.jpg',
  'Électricien intervenant sur une installation basse tension avec EPI',
  '14 heures (2 jours)',
  'Électriciens / techniciens de maintenance — 4 à 10 personnes par session',
  NULL,
  'Être électricien ou technicien de maintenance amené à réaliser des travaux BT',
  '550 € HT (indiv.) · 1 700 € HT (4-6 pers.) · 2 400 € HT (7-10 pers.)',
  'Présentiel — sur site client (60 % de pratique)',
  '7 jours avant la session',
  'Tous les 3 ans, ou si absence supérieure à 6 mois au poste',
  'À l''issue de la formation, le stagiaire est capable de réaliser en sécurité des opérations électriques en basse tension conformément à la norme NF C18-510. La formation prépare aux habilitations B1V (exécutant électricien — travaux hors tension au voisinage de pièces nues sous tension) et B2V (chargé de travaux — direction et surveillance d''une équipe en voisinage).',
  '[{"titre":"Connaissance des risques électriques","points":["Effets physiopathologiques du courant sur le corps humain","Domaines de tension BT/TBT, contacts directs et indirects","Brûlures, électrisation, électrocution — comprendre les risques","Réglementation : norme NF C18-510 et Code du travail"]},{"titre":"Niveaux d''habilitation, zones & équipements","points":["Rôles B1V / B2V — autorisations et interdictions","Chargé d''exploitation, chargé de consignation (BC)","Zones d''environnement, de sécurité et de voisinage renforcé (ZSR)","EPI et EPC — outillage isolant, signalisation électrique"]},{"titre":"Procédures d''opérations électriques","points":["Mise hors tension, mise hors de portée, consignation","Attestation de consignation, avis de fin de travaux, autorisation de travail","Analyse des risques avant intervention","Manœuvres et raccordements autorisés selon habilitation"]},{"titre":"Conduite à tenir en cas d''accident électrique","points":["Protéger, alerter, secourir — réflexes d''urgence","Dégagement d''une victime en milieu électrique","Premiers secours adaptés aux accidents électriques"]}]'::jsonb,
  'Avis d''aptitude après formation délivré à chaque stagiaire, permettant à l''employeur de délivrer l''habilitation B1V et/ou B2V. Épreuves théorique et pratique conformes NF C18-510.',
  'Norme NF C18-510 (décret du 14/11/2011) — Articles R4544-9 et R4544-10 du Code du travail — Arrêté du 26 avril 2012.',
  '["habilitation-electrique-h0-b0","incendie-extincteur-evacuation"]'::jsonb,
  'Habilitation Électrique B1V & B2V | C-KIM Formation',
  'Formation Habilitation Électrique B1V/B2V conforme NF C18-510 à Draguignan (PACA). 14h, 60 % de pratique. Pour électriciens et techniciens de maintenance BT.',
  true,
  60
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Habilitation Électrique — BS BE Manœuvre
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'habilitation-electrique-bs-be-manoeuvre',
  'Habilitation Électrique',
  'BS BE Manœuvre',
  'securite',
  'SECU-05',
  '/images/formations/habilitation-electrique-bs-be-manoeuvre.jpg',
  'Habilitation Électrique BS BE Manœuvre — gant de protection et câble dénudé pour intervention basse tension',
  '14 heures',
  'Tout public',
  'Personnel non électricien réalisant des interventions élémentaires (remplacement, raccordement) et/ou des manœuvres en basse tension sur des installations électriques.',
  'Aptitude médicale. Pas de prérequis pour le symbole BE manœuvre. Pour le symbole BS : connaissance des règles élémentaires de l''électricité et des techniques de remplacement et raccordement sur les installations concernées.',
  'Sur devis',
  'Présentiel — sur site client',
  '7 jours avant la session',
  'Recyclage recommandé tous les 3 ans (NF C 18-510)',
  'Exécuter en sécurité des interventions de remplacement et de raccordement simples et des manœuvres dans le respect des textes et de la norme NF C 18-510.',
  '[{"titre":"Notions élémentaires d''électricité","points":["Risques liés à l''électricité et accidents du travail associés","Effets de l''électrisation sur le corps humain","Définition des habilitations électriques et leurs objectifs","Les différents matériels et leurs domaines de tension","Unités usuelles, points de mesure, loi d''Ohm","Fonctions des matériels électriques BT et HT"]},{"titre":"Travailler en sécurité dans un environnement électrique","points":["Règles de sécurité pour se prémunir du danger","Zones d''environnement et leurs limites","Séquences de mise hors tension","Réalisation d''une VAT (vérification d''absence de tension)","Réalisation d''une remise sous tension","Équipements de protection collective et individuelle"]},{"titre":"Raccordement, remplacement, manœuvre en sécurité","points":["Mesures de prévention lors d''une intervention","Documents, instructions de sécurité et EPI nécessaires","Remplacer un fusible, une lampe, un accessoire","Réaliser un raccordement hors tension","Réaliser une manœuvre haute ou basse tension"]},{"titre":"Réagir face à un accident","points":["Conduite à tenir en cas d''incident sur l''équipage électrique","Conduite à tenir en cas d''accident d''origine électrique","Réagir en cas d''accident sur les ouvrages électriques"]}]'::jsonb,
  'Évaluation théorique et pratique en fin de formation. Avis après formation conforme à la norme NF C 18-510, attestation de formation et enquête de satisfaction stagiaire.',
  'L''habilitation électrique est une exigence réglementaire pour tous les travailleurs effectuant des opérations sur les installations électriques ou dans leur voisinage. Elle nécessite une formation préalable. La norme NF C 18-510 préconise un recyclage tous les 3 ans.',
  '["habilitation-electrique-h0-b0","habilitation-electrique-b1v-b2v","incendie-extincteur-evacuation"]'::jsonb,
  'Habilitation Électrique BS BE Manœuvre | C-KIM Formation',
  'Formation habilitation électrique BS / BE Manœuvre — 14h, présentiel, conforme NF C 18-510. Pour interventions élémentaires et manœuvres en basse tension. Région PACA.',
  true,
  70
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Hygiène Alimentaire — Méthode HACCP
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'hygiene-alimentaire-haccp',
  'Hygiène Alimentaire',
  'Méthode HACCP',
  'alimentaire',
  'SECU-05',
  '/images/formations/hygiene-alimentaire-haccp.jpg',
  'Cuisine professionnelle et application des bonnes pratiques d''hygiène HACCP',
  '14 heures (2 jours) — J1 : Hygiène & BPH, J2 : HACCP',
  'Tout professionnel manipulant des denrées alimentaires (cuisine, restauration, bar, réception) — 4 à 10 personnes',
  NULL,
  'Aucun',
  '350 € HT (indiv.) · 1 500 € HT (4-6 pers.) · 2 200 € HT (7-10 pers.)',
  'Présentiel — sur site client',
  '7 jours avant la session',
  'Tous les 3 ans',
  'À l''issue de la formation, le stagiaire est capable d''appliquer les bonnes pratiques d''hygiène, de mettre en œuvre la méthode HACCP et de prévenir les risques de contamination alimentaire conformément au Règlement CE 852/2004.',
  '[{"titre":"Cadre réglementaire","points":["Règlement CE 852/2004 et paquet hygiène européen","Obligations de l''exploitant — responsabilités en cas de TIAC","Traçabilité des denrées — obligation, mise en place, conservation"]},{"titre":"Microbiologie alimentaire","points":["Micro-organismes pathogènes : Salmonelles, Listeria, E. coli, Staphylocoques…","Conditions de développement et de multiplication bactérienne","TIAC : causes, conséquences, prévention"]},{"titre":"Bonnes Pratiques d''Hygiène (BPH)","points":["Hygiène personnelle : tenue, lavage des mains, état de santé","Nettoyage et désinfection : méthodes, produits, plan de nettoyage","Gestion des déchets et nuisibles — chaîne du froid — marche en avant"]},{"titre":"Les 7 principes HACCP","points":["P1 : Analyser les dangers (biologiques, chimiques, physiques)","P2 : Identifier les Points Critiques de Contrôle (CCP)","P3 : Établir les limites critiques — P4 : Système de surveillance","P5 : Actions correctives — P6 : Vérification — P7 : Documentation"]},{"titre":"Application pratique sur cas réel","points":["Construction d''un diagramme de fabrication et identification des CCP","Rédaction d''une fiche de surveillance CCP","Gestion d''une non-conformité et traçabilité"]}]'::jsonb,
  'QCM de validation des acquis + exercices pratiques HACCP. Attestation individuelle envoyée numériquement à chaque stagiaire.',
  'Règlement CE 852/2004 (paquet hygiène européen) — Arrêté du 5 octobre 2011 relatif à l''obligation de formation en hygiène alimentaire dans la restauration commerciale — Code rural et de la pêche maritime.',
  '["incendie-extincteur-evacuation"]'::jsonb,
  'Formation Hygiène Alimentaire HACCP | C-KIM Formation',
  'Formation HACCP obligatoire pour la restauration et l''agroalimentaire. 14h, sur site client en PACA. Conformité Règlement CE 852/2004 et arrêté du 5 octobre 2011.',
  true,
  80
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- DUERP — Formation — & Accompagnement Clé en Main
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'duerp-formation-accompagnement',
  'DUERP — Formation',
  '& Accompagnement Clé en Main',
  'prevention',
  'PREV-01',
  '/images/formations/duerp-formation-accompagnement.jpg',
  'Réunion d''évaluation des risques professionnels et rédaction du Document Unique',
  '21 heures (3 jours) — J1 & J2 formation (14h), J3 accompagnement sur site (7h)',
  'Dirigeant, responsable d''établissement, référent sécurité, RH — 1 à 5 personnes',
  NULL,
  'Aucun — idéalement, accès aux informations de l''entreprise',
  '1 800 € HT (4-6 pers.) · 2 500 € HT (7-10 pers.) — DUERP finalisé inclus',
  'Présentiel — formation + accompagnement sur site',
  '15 jours avant la session',
  'Mise à jour annuelle obligatoire et à chaque changement important',
  'À l''issue de la formation, le stagiaire est capable de réaliser, de mettre à jour et d''exploiter son Document Unique d''Évaluation des Risques Professionnels de manière autonome, en conformité avec les articles R4121-1 et R4121-2 du Code du travail. Le DUERP est livré finalisé en PDF et Word modifiable à l''issue du jour 3.',
  '[{"titre":"Jour 1 — Cadre réglementaire & Méthodologie (7h)","points":["Cadre juridique : obligation du DUERP, qui est concerné, quand le mettre à jour","Responsabilités de l''employeur et sanctions en cas d''absence du document","Définition des unités de travail (UT) — découper l''entreprise par zones / activités","Identification des dangers : physiques, chimiques, biologiques, psychosociaux, organisationnels","Méthode de cotation des risques : probabilité × gravité → niveau de criticité","Hiérarchisation et priorisation des actions de prévention"]},{"titre":"Jour 2 — Rédaction & Plan d''action (7h)","points":["Structure du DUERP : présentation, unités de travail, tableau de cotation, plan d''action","Rédaction des fiches de risques par unité de travail (cas pratiques)","Construction du plan d''actions correctives et préventives (responsable, délai, coût)","Intégration des accidents du travail et maladies professionnelles passés","Modalités de mise à jour et présentation au CSE"]},{"titre":"Jour 3 — Accompagnement sur site & Livraison (7h)","points":["Visite complète de l''établissement avec le formateur — repérage terrain","Identification des risques spécifiques à l''activité","Co-rédaction en temps réel des fiches de risques par unité de travail","Finalisation du tableau de cotation et du plan d''actions","Livraison du DUERP finalisé en PDF + Word modifiable"]}]'::jsonb,
  'Livrables inclus : DUERP finalisé livré en PDF + Word modifiable, attestation de formation, feuille de route de mise à jour annuelle. Conservation obligatoire 40 ans (Loi du 2 août 2021).',
  'Articles R4121-1 et R4121-2 du Code du travail — Loi n° 2021-1018 du 2 août 2021 (renforcement de la prévention en santé au travail) — Articles L4121-1 à L4121-5 (obligation générale de sécurité de l''employeur).',
  '["elaboration-duerp-manager-sst"]'::jsonb,
  'DUERP — Formation & Accompagnement Clé en Main | C-KIM Formation',
  'Formation DUERP avec accompagnement sur site et livraison du Document Unique finalisé. Forfait 1 500 € HT, conformité Code du travail (R4121-1).',
  true,
  90
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Élaboration DUERP — & Manager Santé & Sécurité au Travail
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'elaboration-duerp-manager-sst',
  'Élaboration DUERP',
  '& Manager Santé & Sécurité au Travail',
  'management',
  'MANSST/06-25/CD',
  '/images/formations/elaboration-duerp-manager-sst.jpg',
  'Manager animant une démarche prévention et santé-sécurité au travail',
  '14 à 21 heures (2 à 3 jours)',
  'Managers de proximité, encadrants, référents prévention — 4 à 10 personnes',
  NULL,
  'Compétences de base en prévention INRS (eformation-inrs.fr) — être manager ou en cours de le devenir',
  '1 100 € HT (4-6 pers.) · 1 600 € HT (7-10 pers.)',
  'Présentiel — sur site client',
  '15 jours avant la session',
  'Mise à jour conseillée tous les 24 mois',
  'À l''issue de la formation, le stagiaire est capable d''appliquer son rôle de manager et de participer activement à la démarche de prévention de l''entreprise, de maîtriser les principes fondamentaux de la prévention des risques professionnels, d''inscrire son rôle de manager S&ST dans la démarche de prévention et de mettre en place une communication S&ST efficace. La formation aborde également l''élaboration et la mise à jour du DUERP.',
  '[{"titre":"Introduction — Cadre réglementaire & rôle du manager","points":["Réglementation de la prévention","Rôles et missions du manager de proximité"]},{"titre":"Module 1 — Fondamentaux de la prévention","points":["Cadre légal — 4 enjeux de la prévention","Conséquences AT/MP/TMS/RPS"]},{"titre":"Module 2 — Démarche de prévention du manager S&ST","points":["Posture, rôle, responsabilité du manager","Communication S&ST — fédérer ses équipes autour de la sécurité"]},{"titre":"Module 3 — Respect des règles & évaluation des risques","points":["Leadership sécurité — EPI","DUERP — élaboration, structure, mise à jour","Outils AT/MP : MAD, arbre des causes"]}]'::jsonb,
  'Évaluation formative continue + épreuve sommative le dernier jour. Certificat de réalisation + Attestation de compétences.',
  'Articles L4121-1 à L4121-5 et R4121-1 à R4121-2 du Code du travail — Loi du 2 août 2021 — Référentiel INRS pour les compétences de base en prévention.',
  '["duerp-formation-accompagnement"]'::jsonb,
  'Élaboration DUERP & Manager S&ST | C-KIM Formation',
  'Formation Manager Santé & Sécurité au Travail couplée à l''élaboration du DUERP. 14 à 21h sur site, certifiée Qualiopi. Pour managers de proximité.',
  true,
  100
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Formateur Sauveteur Secouriste du Travail — FO SST — Certification INRS
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'formateur-sst',
  'Formateur Sauveteur Secouriste du Travail',
  'FO SST — Certification INRS',
  'formateurs',
  'FOSST/01-26/VP',
  '/images/formations/formateur-sst.jpg',
  'Formation de formateurs SST avec mannequin de réanimation et gestes de premiers secours',
  '56 heures minimum (2 semaines, 2 × 4 jours non consécutifs)',
  'Tout salarié souhaitant devenir formateur SST — 5 à 10 personnes maximum',
  NULL,
  'Certificat SST à jour + compétences de base en prévention INRS + capacités relationnelles et d''animation',
  'Sur devis',
  'Présentiel — habilitation INRS uniquement (animation sous habilitation)',
  '15 jours avant la session',
  'MAC FO SST tous les 36 mois',
  'À l''issue de la formation, le stagiaire est capable de déployer le dispositif SST dans sa globalité, de démontrer l''intérêt de la formation SST pour une entreprise, de maîtriser les aspects méthodologiques et techniques de la prévention et du secours, et de concevoir, animer, évaluer et suivre une action de formation SST.',
  '[{"titre":"Introduction — Dispositif SST & FORPREV","points":["Organisation du dispositif SST — processus d''habilitation et FORPREV","Rôles et missions du formateur SST interne ou d''un organisme de formation habilité"]},{"titre":"DC1 — Démontrer l''intérêt de la formation SST pour une entreprise","points":["Justifier la formation SST : intérêts, enjeux humains, juridiques et économiques","Répondre à la demande de formation SST en tenant compte des spécificités"]},{"titre":"DC2 — Maîtriser les aspects méthodologiques & techniques","points":["S''appuyer sur le guide des données techniques pour mettre en œuvre une action de secours","Justifier la mise en place d''actions de prévention — identification des risques"]},{"titre":"DC3 — Concevoir, animer, évaluer & suivre une action SST","points":["Concevoir un déroulé pédagogique SST — documents cadres INRS","Animer une action SST — préparation, mise en œuvre, gestion des dysfonctionnements","Méthodes d''évaluation formatives et certificatives — gestion FORPREV 2"]}]'::jsonb,
  'Évaluation formative continue (grille individuelle INRS) + Épreuve certificative 1 (1er jour semaine 2) + Épreuve certificative 2 (4e jour semaine 2). Obtention : Certificat de Formateur SST INRS + Certificat de réalisation. Permet d''animer uniquement sous une habilitation délivrée par l''INRS.',
  'Référentiel INRS — Document de référence du dispositif de formation SST — Articles R4224-15 et R4224-16 du Code du travail (sauveteurs secouristes du travail).',
  '["mac-formateur-sst","formateur-incendie-gestes-postures","formateur-independant-interne"]'::jsonb,
  'Formateur SST — Certification INRS | C-KIM Formation',
  'Devenir Formateur Sauveteur Secouriste du Travail certifié INRS. 56h, 70 % de pratique, en PACA. Habilitation INRS et certificat de Formateur SST à la clé.',
  true,
  110
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Maintien & Actualisation des Compétences — MAC FO SST — Recyclage Formateur SST
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'mac-formateur-sst',
  'Maintien & Actualisation des Compétences',
  'MAC FO SST — Recyclage Formateur SST',
  'formateurs',
  'MFOSST/01-26/VP',
  '/images/formations/mac-formateur-sst.jpg',
  'Recyclage de formateurs SST — pratique des gestes de premiers secours',
  '21 heures minimum (3 jours consécutifs)',
  'Formateurs SST certifiés souhaitant renouveler leur certificat — 5 à 10 personnes maximum',
  NULL,
  'Être titulaire du certificat de formateur SST délivré par une entité habilitée INRS + compétences de base en prévention',
  'Sur devis',
  'Présentiel — habilitation INRS',
  '15 jours avant la session',
  'Obligatoire tous les 36 mois',
  'À l''issue de la formation, le stagiaire est capable de déployer le dispositif SST dans sa globalité en tenant compte des évolutions INRS, d''actualiser ses compétences de formateur SST conformément à la réglementation, et d''appliquer les évolutions du programme SST défini par l''INRS.',
  '[{"titre":"Introduction — Retour d''expérience (Brise-glace)","points":["Tour de table : chaque formateur présente oralement une action de formation SST mise en œuvre","Retour d''expérience collectif — partage des pratiques et des difficultés rencontrées"]},{"titre":"Module 1 — Démontrer l''intérêt de la formation SST","points":["Justifier, en s''appuyant sur son expérience, l''intérêt des actions de formation SST","Argumenter dans les domaines de la prévention et du secours auprès des entreprises","Présenter les bénéfices du réseau SST pour l''entreprise et ses salariés"]},{"titre":"Module 2 — Maîtrise des aspects méthodologiques & techniques","points":["Utilisation du Guide des données techniques lors des actions SST et MAC SST","Maîtriser les outils d''animation de la prévention : PISST, PAP, Tuto''Prev…","Intégrer les évolutions réglementaires et techniques définies par l''INRS"]},{"titre":"Module 3 — Concevoir, animer, évaluer & suivre une action SST","points":["Concevoir ou utiliser un déroulé pédagogique SST intégrant les évolutions","Animer une séquence de formation SST — animations du PISST et du PAP en situation","Travaux en sous-groupes et mises en situations d''animation pratiques"]}]'::jsonb,
  'Évaluation formative continue sur grille individuelle + Épreuve certificative 1 (J1) + Épreuve certificative 2 (J3). Résultats transmis à l''INRS. Renouvellement du Certificat Formateur SST + Certificat de réalisation.',
  'Référentiel INRS — Document de référence du dispositif de formation SST — Obligation de MAC tous les 36 mois pour conserver l''habilitation INRS.',
  '["formateur-sst","formateur-incendie-gestes-postures","formateur-independant-interne"]'::jsonb,
  'MAC FO SST — Recyclage Formateur SST | C-KIM Formation',
  'Maintien et Actualisation des Compétences du Formateur SST — recyclage INRS obligatoire tous les 36 mois. 21h en présentiel en PACA.',
  true,
  120
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Formateur Sécurité Incendie — & Gestes & Postures
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'formateur-incendie-gestes-postures',
  'Formateur Sécurité Incendie',
  '& Gestes & Postures',
  'formateurs',
  'FOSI-FOGP/01-26',
  '/images/formations/formateur-incendie-gestes-postures.jpg',
  'Formation de formateurs incendie et ergonomie — gestes et postures de prévention TMS',
  '28 heures (4 jours) — option Sanitaire & Social +7h pour Gestes & Postures',
  'Futurs formateurs sécurité incendie ou gestes & postures — 3 à 10 personnes',
  NULL,
  'Compétences de base en prévention INRS — pour Gestes & Postures : avoir suivi une formation Gestes & Postures',
  'Sur devis',
  'Présentiel — sur site C-KIM ou client',
  '15 jours avant la session',
  'Conseillé tous les 36 mois',
  'Cette double certification permet de devenir formateur en Sécurité Incendie et/ou en Gestes & Postures (prévention des TMS). À l''issue de la formation, le stagiaire est capable d''identifier les règles qualité de la formation (Qualiopi), de concevoir des actions de formation incendie ou Gestes & Postures adaptées, d''animer et d''évaluer ces actions, et de créer ses propres supports et outils pédagogiques.',
  '[{"titre":"Module 1 — Concevoir, animer & évaluer (commun)","points":["Règles qualité / Qualiopi — ingénierie pédagogique","Conditions d''apprentissage de l''adulte — méthodes pédagogiques","Concevoir programme et déroulé — évaluation des acquis"]},{"titre":"Module 2 — Enjeux prévention incendie","points":["Enjeux humains, juridiques, économiques, sociétaux","Réglementation incendie applicable — impact réel d''un sinistre"]},{"titre":"Module 3 — Concevoir & animer une formation incendie","points":["Contenu adapté — particularités sectorielles","Mise en situation d''animation le dernier jour"]},{"titre":"Module 4 — Concevoir, animer & évaluer une formation Gestes & Postures","points":["Conditions d''apprentissage de l''adulte — ingénierie de formation appliquée à la prévention TMS","Concevoir programme et contenu — ergonomie, économie d''effort","Animer une action G&P — différents types d''évaluation"]},{"titre":"Option Sanitaire & Social (+7h)","points":["Particularités du secteur sanitaire et social","Aides à la manipulation de personnes — utilisation et formation","Animer et évaluer avec les aides techniques"]}]'::jsonb,
  'Évaluation formative continue + mise en situation d''animation (épreuve sommative). Certificat de Formateur Sécurité Incendie et/ou Certificat de réalisation Formateur Gestes et Postures.',
  'Article R4541-8 du Code du travail (formation à la sécurité — manutention manuelle) — Référentiel Qualiopi (RNQ) — Articles R4227-28 et R4227-39 du Code du travail (incendie).',
  '["formateur-sst","mac-formateur-sst","formateur-independant-interne"]'::jsonb,
  'Formateur Sécurité Incendie & Gestes Postures | C-KIM Formation',
  'Devenir formateur en Sécurité Incendie ou en Gestes & Postures (prévention TMS). 28h + option Sanitaire & Social. Certifié Qualiopi en PACA.',
  true,
  130
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Formateur Indépendant — et / ou Interne — Ingénierie de Formation & Pédagogie
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'formateur-independant-interne',
  'Formateur Indépendant',
  'et / ou Interne — Ingénierie de Formation & Pédagogie',
  'formateurs',
  'FOIND/04-25/CD',
  '/images/formations/formateur-independant-interne.jpg',
  'Formateur indépendant animant une session de formation pour adultes en entreprise',
  '35 heures (adaptable selon analyse des besoins)',
  'Toute personne souhaitant devenir formateur indépendant ou formateur interne — 2 à 8 personnes maximum',
  NULL,
  'Maîtrise des outils informatiques de base + capacités relationnelles, d''animation et d''expression (évaluées par entretien)',
  'Sur devis',
  'Présentiel / Distanciel / Mixte',
  '15 jours avant + entretien de positionnement',
  'Conseillé tous les 36 mois',
  'À l''issue de la formation (60 % de pratique), le stagiaire est capable d''identifier les besoins des futurs bénéficiaires et de définir des objectifs opérationnels adaptés, de concevoir une ingénierie pédagogique adaptée aux objectifs, d''animer une action de formation en s''appuyant sur son ingénierie, et de définir des modalités d''évaluation pour chaque bénéficiaire. Certification : Formateur de Formateurs Qualiopi.',
  '[{"titre":"Introduction — Cadre réglementaire & rôle du formateur","points":["Réglementation de la formation professionnelle continue et démarche qualité","Rôles et missions du formateur externe et interne"]},{"titre":"Module 1 — Ingénierie de formation","points":["Créer son questionnaire d''analyse des besoins","Identifier les objectifs stratégiques lors de la demande de formation","Définir des objectifs opérationnels et évaluables"]},{"titre":"Module 2 — Ingénierie pédagogique","points":["De la pédagogie vers l''andragogie — conditions d''apprentissage de l''adulte","Méthodes et techniques pédagogiques — identifier les personnalités du public","Identifier ou créer des outils d''animation — méthodes d''évaluation","Définir une progression pédagogique"]},{"titre":"Module 3 — Animer son déroulé pédagogique","points":["Définir un mode d''animation adapté (présentiel, distanciel…)","Animer une action de formation : préparation, mise en œuvre, gestion des dysfonctionnements","Mettre en œuvre différentes méthodes d''évaluation"]},{"titre":"Module 4 — Veille réglementaire & métier","points":["Veille réglementaire — veille métier — veille pédagogique"]}]'::jsonb,
  'Évaluation formative continue (grille individuelle) + épreuve sommative le dernier jour (mise en situation d''animation). Certificat de réalisation de formateur + Attestation de compétences.',
  'Formation professionnelle continue — Article L.6311-1 du Code du travail — Qualiopi — Référentiel National Qualité (RNQ).',
  '["formateur-sst","formateur-incendie-gestes-postures","formateur-professionnel-adultes-fpa"]'::jsonb,
  'Formateur Indépendant et / ou Interne | C-KIM Formation',
  'Formation Formateur de Formateurs (35h) — ingénierie de formation et pédagogie pour devenir formateur indépendant ou interne. Certifiée Qualiopi en PACA.',
  true,
  140
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- PNL — Programmation Neuro-Linguistique — Développement Personnel & Communication
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'pnl-controle-qualiopi',
  'PNL — Programmation Neuro-Linguistique',
  'Développement Personnel & Communication',
  'developpement',
  'DEV-01',
  '/images/formations/pnl-controle-qualiopi.jpg',
  'Séance de coaching et de communication interpersonnelle inspirée des outils PNL',
  '21 heures (3 jours)',
  'Toute personne souhaitant améliorer sa communication et son développement personnel — 4 à 10 personnes',
  NULL,
  'Aucun',
  '320 € HT (indiv.) · Groupe : sur devis',
  'Présentiel — 80 % de pratique',
  '7 jours avant la session',
  'Conseillé tous les 2 ans',
  'À l''issue de la formation, le stagiaire est capable d''identifier ses schémas de pensée et de communication, d''utiliser les outils PNL pour améliorer ses relations professionnelles et personnelles, et de dépasser ses blocages pour initier des changements durables.',
  '[{"titre":"Jour 1 — Fondements de la PNL & Connaissance de soi","points":["Histoire et fondements — Bandler, Grinder, Dilts","Présupposés PNL — systèmes VAKOG — filtres mentaux","États internes, calibration, rapport (synchronisation) — métaprogrammes"]},{"titre":"Jour 2 — Communication & Outils de changement","points":["Méta-modèle du langage — modèle Milton — niveaux logiques de Dilts","Ancrage — dissociation — swish pattern — ligne du temps"]},{"titre":"Jour 3 — Croyances, objectifs & mise en pratique","points":["Identifier et changer ses croyances limitantes — submodalités","Objectifs bien formés — plan d''action personnel","Mises en situation : entretiens, négociation, gestion de conflits"]}]'::jsonb,
  'Évaluation continue + questionnaire d''auto-évaluation avant/après. Attestation de formation + Plan d''action personnel individualisé.',
  'Formation au titre de la formation professionnelle continue — Article L.6313-1 du Code du travail — Démarche qualité Qualiopi (RNQ).',
  '["preparer-controle-qualiopi"]'::jsonb,
  'PNL — Programmation Neuro-Linguistique | C-KIM Formation',
  'Formation PNL en 3 jours (21h) — communication, développement personnel, gestion des croyances limitantes. 80 % de pratique en PACA.',
  true,
  150
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Préparer un Contrôle Qualité — Qualiopi — Référentiel National Qualité (RNQ)
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'preparer-controle-qualiopi',
  'Préparer un Contrôle Qualité',
  'Qualiopi — Référentiel National Qualité (RNQ)',
  'qualite',
  'QUAL/08-25/CD',
  '/images/formations/preparer-controle-qualiopi.jpg',
  'Audit qualité Qualiopi — préparation et revue de procédures internes',
  '14 à 49 heures (modulable selon besoins)',
  'Dirigeants et responsables qualité d''organismes de formation — 1 à 5 personnes',
  NULL,
  'Lire, écrire, compter — connaissances du fonctionnement d''un organisme de formation',
  'Sur devis',
  'Présentiel — 60 % de pratique — animée par un auditeur AFNOR',
  '15 jours avant la session',
  'Avant chaque audit de surveillance ou de renouvellement',
  'À l''issue de la formation, le stagiaire est capable d''identifier les enjeux d''une démarche qualité et de maîtriser les 7 critères du Référentiel National Qualité, de s''approprier et de réorganiser les procédures internes de son organisme, d''assurer la continuité et l''amélioration de la démarche qualité, et de préparer sereinement un audit ou un audit de contrôle Qualiopi.',
  '[{"titre":"Introduction — Cadre RNQ & organisation audit","points":["Les 7 critères Qualiopi — organisation d''un audit qualité"]},{"titre":"Module 1 — Enjeux de la démarche qualité","points":["OPCO et financement — obligations réglementaires","La qualité comme levier de développement"]},{"titre":"Module 2 — Procédures internes","points":["S''approprier, créer ou restructurer son système qualité"]},{"titre":"Module 3 — Continuité & amélioration","points":["Analyser le rapport d''audit — lever une non-conformité","Amélioration continue"]},{"titre":"Module 4 — Audit blanc (simulation complète)","points":["Organiser l''audit avec son personnel — définir les interlocuteurs","Participer à un audit blanc — justifier oralement les écarts"]}]'::jsonb,
  'Évaluation formative continue + audit blanc le dernier jour. Certificat de réalisation + Attestation de compétences. Accompagnement post-formation possible.',
  'Décret n° 2019-565 du 6 juin 2019 relatif au Référentiel National Qualité — Loi du 5 septembre 2018 (Avenir professionnel) — Articles L.6316-1 et suivants du Code du travail — Référentiel Qualiopi (RNQ).',
  '["pnl-controle-qualiopi","formateur-independant-interne"]'::jsonb,
  'Préparer un Contrôle Qualité Qualiopi (RNQ) | C-KIM Formation',
  'Préparer son audit Qualiopi avec un auditeur AFNOR : 7 critères RNQ, audit blanc, plan d''action. 14 à 49h modulables en PACA.',
  true,
  160
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;

-- Formateur Professionnel d'Adultes — FPA — Titre Professionnel RNCP Niveau 5 (Bac+2)
INSERT INTO public.formations (
  slug, titre, sous_titre, parcours, ref, hero_image, hero_alt,
  duree, public_concerne, public_detail, prerequis, prix_indicatif,
  modalite, inscription, recyclage,
  objectifs, programme, evaluation, references_reglementaires, formations_liees,
  seo_title, seo_description, actif, ordre
) VALUES (
  'formateur-professionnel-adultes-fpa',
  'Formateur Professionnel d''Adultes',
  'FPA — Titre Professionnel RNCP Niveau 5 (Bac+2)',
  'certifiant',
  'FPA-01/26/CKIM',
  '/images/formations/formateur-professionnel-adultes-fpa.jpg',
  'Salle de formation pour adultes — animation pédagogique et certification FPA',
  '812 heures (29 semaines) — formation modulaire, durée adaptable',
  'Toute personne souhaitant exercer le métier de formateur professionnel — 8 à 12 personnes maximum',
  NULL,
  'Niveau Bac minimum ou 3 ans d''expérience professionnelle + entretien de positionnement obligatoire',
  '6 000 € HT (parcours 29 semaines) — financement CPF, OPCO, France Travail, Région Sud',
  'Présentiel / Distanciel / Mixte',
  '15 jours avant + entretien de positionnement',
  'Titre professionnel valable à vie — veille pédagogique conseillée',
  'Cette formation certifiante (70 % de pratique) prépare au Titre Professionnel Formateur Professionnel d''Adultes (RNCP37274 — Niveau 5, Bac+2). À l''issue du parcours, le stagiaire est capable de concevoir des dispositifs et séquences de formation adaptés aux besoins des apprenants, d''animer une formation en présentiel, distanciel ou mixte, d''accompagner les apprenants dans leur parcours, d''évaluer les acquis et les résultats, et d''inscrire son activité dans la démarche qualité Qualiopi.',
  '[{"titre":"Bloc 1 — Analyser les besoins et concevoir des dispositifs de formation","points":["Analyser la demande — définir des objectifs pédagogiques opérationnels","Concevoir le dispositif et le programme — choisir les modalités (présentiel, distanciel, AFEST)","Concevoir outils et supports attractifs — intégrer la démarche Qualiopi"]},{"titre":"Bloc 2 — Animer une formation et créer les conditions d''apprentissage","points":["Maîtriser les techniques d''animation — gérer la dynamique de groupe","Animer en distanciel et en mode hybride — outils numériques, LMS","Intégrer la Ludopédagogie et les outils interactifs en formation"]},{"titre":"Bloc 3 — Évaluer les acquis et les résultats de la formation","points":["Évaluations formatives, sommatives et certificatives","Mesurer la satisfaction (questionnaires à chaud et à froid)","Renseigner les outils de suivi Qualiopi"]},{"titre":"Bloc 4 — Accompagner les apprenants et gérer son activité de formateur","points":["Tutorat, suivi individuel, adaptation aux difficultés d''apprentissage","Gestion administrative, juridique et fiscale du formateur indépendant","Veille pédagogique, réglementaire et métier — développement du réseau professionnel"]}]'::jsonb,
  'Mise en situation professionnelle devant jury + Rapport d''activité écrit + Entretien final oral devant jury certificateur. Obtention : Titre RNCP Niveau 5 — Formateur Professionnel d''Adultes. Débouchés : formateur en organisme, formateur interne, indépendant, consultant, coordinateur ou responsable formation.',
  'Titre Professionnel Formateur Professionnel d''Adultes — RNCP37274 — NSF 332 — Niveau 5 (Bac+2) — Reconnu par France Compétences — Articles L.6313-1 et suivants du Code du travail — Référentiel Qualiopi (RNQ).',
  '["formateur-independant-interne","preparer-controle-qualiopi"]'::jsonb,
  'FPA — Formateur Professionnel d''Adultes (RNCP Niveau 5) | C-KIM Formation',
  'Titre Professionnel Formateur Professionnel d''Adultes — RNCP37274 Niveau 5 (Bac+2). 812h, 4 blocs, financement CPF/OPCO. Centre certifié Qualiopi en PACA.',
  true,
  170
)
ON CONFLICT (slug) DO UPDATE SET
  titre = EXCLUDED.titre,
  sous_titre = EXCLUDED.sous_titre,
  parcours = EXCLUDED.parcours,
  ref = EXCLUDED.ref,
  hero_image = EXCLUDED.hero_image,
  hero_alt = EXCLUDED.hero_alt,
  duree = EXCLUDED.duree,
  public_concerne = EXCLUDED.public_concerne,
  public_detail = EXCLUDED.public_detail,
  prerequis = EXCLUDED.prerequis,
  prix_indicatif = EXCLUDED.prix_indicatif,
  modalite = EXCLUDED.modalite,
  inscription = EXCLUDED.inscription,
  recyclage = EXCLUDED.recyclage,
  objectifs = EXCLUDED.objectifs,
  programme = EXCLUDED.programme,
  evaluation = EXCLUDED.evaluation,
  references_reglementaires = EXCLUDED.references_reglementaires,
  formations_liees = EXCLUDED.formations_liees,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  ordre = EXCLUDED.ordre;
